### PR TITLE
Real time apps with polymer and firebase

### LINKED ISSUE #196: Add Talk  High Performance Web Components
HTML5 Dev Conf -Steve Souders
https://www.youtube.com/watch?v=m3EPIeKaDCU

### LINKED ISSUE #197: Web Components LA Meetup : Polymer & Firebase
http://youtu.be/gErWcBdd-F8

### PR DESCRIPTION
**Pull request by Nevraeka**
Added 2 presentations 

- Real-Time Apps with Firebase and Polymer - Web Components LA - @mbleigh
- High Performance Web Components - HTML5DevConf - @stevesouders
 
closes #196
closes #197

### CODE REVIEW

**Comment by zenorocha** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by zenorocha** [comment]
Awesome job! Thanks @Nevraeka :D

**Comment by zenorocha** [comment]
Thank you, pull request merged! <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by Nevraeka** [comment]
Thank you

**Pull request closed without merging**
