### PR TITLE
Adds article about Q1 numbers

### PR DESCRIPTION
**Pull request by zenorocha**
Could anyone review it? Do you think it is a good idea?

### CODE REVIEW

**Comment by mateusortiz** [comment]
Yes it is a good idea, just my name that is not with h, only Mateus :satisfied:

**Comment by zenorocha** [comment]
Oops, fixed!

**Comment by Nevraeka** [comment]
reviewing now : )

**Comment by Nevraeka** [comment]
Left comments on the commit. Please check it out @zenorocha and we will need to merge with site after the first deploy today. Thanks

**Comment by zenorocha** [comment]
Changes applied, thanks @Nevraeka!

**Pull request merged**
