### PR TITLE
web components book article

### PR DESCRIPTION
**Pull request by jstrimpel**
@zenorocha extremely later, but here it is. https://twitter.com/zenorocha/status/573190999054397440

### CODE REVIEW

**Comment by Nevraeka** [comment]
Overall, this is a well done article & PR but I'm not sure if it is the place for this. I wonder if we need a shop section that could replace swag (just links to web components merchandise) . 

@jstrimpel - On a minor note we would need a real picture of the author & links that go to new windows/tabs if we were to merge this PR.

cc @addyosmani @zenorocha

**Comment by jstrimpel** [comment]
I can reshape to be more focused on the conversion of a widget to web component at a high level with a mention of the book in the closing. If that is of interest let me know, and I will update my author data as well.

**Comment by Nevraeka** [comment]
@jstrimpel that sounds good if we want to put the content in this section. We are juggling a lot right now so let me get back to you next week. Thanks

**Comment by Nevraeka** [comment]
@zenorocha - where does the content for this belong?

**Comment by Nevraeka** [comment]
@jstrimpel - I apologize for the massive delay on this. Please let me know if you need updates to the article. I am happy to add them myself or accept a PR. Whatever works for best.

**Pull request merged**
