### PR TITLE
Podcast section 

### PR DESCRIPTION
**Pull request by Nevraeka**
This is based on PR #210

### CODE REVIEW

**Comment by Nevraeka** [comment]
Are we waiting on the events section before this gets rolled in?

**Comment by zenorocha** [comment]
I always waiting for a UI revamp in the menu bar and search box but it might take more time than I thought. In order to start pushing the Podcast and Meetups section forward, I added this auxiliar navigation in the footer so people can found those new sections until we figure out a better menu bar.

https://github.com/webcomponents/webcomponents.github.io/commit/270b612efe3913eb3b49d98446f5dc7e8d448cf4

**Comment by zenorocha** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by zenorocha** [comment]
- [ ] Setup Feedburner

**Comment by Nevraeka** [comment]
Whose email should I use?

**Comment by zenorocha** [comment]
This is a reminder for me ;)

**Comment by Nevraeka** [comment]
:+1: Thanks

**Comment by zenorocha** [comment]
Merged, deployed and shared!

Thanks for this huge contribution @Nevraeka, I know it took a lot of time to produce it.

We hope you continue contributing and we count on you on curating this section ;D

**Pull request closed without merging**
