### PR TITLE
Adds "Why Web Components" article #60

### PR DESCRIPTION
**Pull request by zenorocha**
Last couple months, @agektmr created a series of introductory articles about each spec. Although those articles were awesome by themselves, we're still missing a primer #60 that introduces developers to the high-level concepts of this Web Components umbrella... specially now that the [Web Components Explainer](https://github.com/w3c/webcomponents/blob/473826ebb096c5231fbe1d67e18837b5f0e35e6c/explainer/index.html) is gone.

This is a proposal to help with that.

### CODE REVIEW

**Comment by zenorocha** [comment]
I'm missing some kind of conclusion after the "Reusability" bullet but I'm not sure exactly what to add. Any ideas @addyosmani? Feel free to pull the branch and add anything.

**Comment by zenorocha** [comment]
When talking to @nevraeka, he made a good point about saying that spec's descriptions are superficial. 

I simplified that on purpose so we could help beginners to understand it quickly. I linked @agektmr twice in order for people to get more information about each spec.

Let me know if you have suggestions to make it more descriptive without compromising beginner's understanding.

**Comment by zenorocha** [comment]
Just added the following conclusion:

> That means we can finally fill any gaps in the platform in a meaningful way. Which also opens an opportunity for a less fragmented ecosystem, where components can truly interoperate with each other.

Good to go?

**Comment by agektmr** [comment]
@zenorocha Sorry I can't help you much now being busy on other stuff, but here's [a video I have done](https://www.youtube.com/watch?v=T5y_lmLngAk) in the past which I think explains overview of Web Components somewhat well. Please consider embedding it if you find it useful.

**Comment by zenorocha** [comment]
Thanks for the reminder @agektmr! Just added a link to that video.

**Pull request merged**
