### PR TITLE
Article: About Polymer + Marionette #193

### PR DESCRIPTION
**Pull request by mateusortiz**
#193

### CODE REVIEW

**Comment by zenorocha** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by zenorocha** [comment]
Did you test before sending the PR? There are bunch of things that needs to be fixed but I'll merge and add some commits on top of it in order to push this faster.

**Comment by zenorocha** [comment]
Thank you, pull request merged! <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by zenorocha** [comment]
Fixes #194 and #193 

/cc @jfairbank @arodic

**Comment by mateusortiz** [comment]
:smile:

**Pull request merged**
