### PR TITLE
Add 'Complementarity of React and Web Components' presentation

### PR DESCRIPTION
**Pull request by andrewrota**
Presented Jan. 29, 2015 at React.js Conf

### CODE REVIEW

**Comment by Nevraeka** [comment]
@andrewrota - You beat me to it! Nice Presentation!

**Comment by zenorocha** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by zenorocha** [comment]
Thank you, pull request merged! <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by zenorocha** [comment]
Awesome, thanks @andrewrota :D

**Comment by zenorocha** [comment]
https://twitter.com/Web_Components/status/564829108371464192
https://plus.google.com/+WebcomponentsOrg/posts/XkxgW7GDtSV

**Pull request closed without merging**
