### PR TITLE
New Article: Introduction to HTML Imports

### PR DESCRIPTION
**Pull request by agektmr**
Here's the final article for series of introduction videos. Please review before pulling it.
Thanks.

### CODE REVIEW

**Comment by agektmr** [comment]
@zenorocha you can pull this now.

**Comment by zenorocha** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by zenorocha** [comment]
Thank you, pull request merged! <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by zenorocha** [comment]
One quick thing, shouldn't we use the polyfill only if the native `currentScript` isn't available?

```js
document.currentScript = document.currentScript || document._currentScript;
```

Instead of:

```js
document._currentScript = document._currentScript || document.currentScript;
```

Here's how we do in `hello-world-element`: https://github.com/webcomponents/hello-world-element/blob/master/src/hello-world.html#L11

**Comment by zenorocha** [comment]
http://webcomponents.org/articles/introduction-to-html-imports/ ;)

**Pull request merged**
