### PR TITLE
Adds article on Shadow DOM Strategies in Angular

### PR DESCRIPTION
**Pull request by PascalPrecht**
**Please don't merge yet**.

The actual post is not published yet, but will be in a couple of hours. I'll comment here once it's out.

@zenorocha do you think we can get this in?

### CODE REVIEW

**Comment by PascalPrecht** [comment]
This can be merged now.

**Comment by PascalPrecht** [comment]
Maybe, @Nevraeka can also take a look

**Comment by Nevraeka** [comment]
THanks @PascalPrecht ! Great read!

**Comment by PascalPrecht** [comment]
\o/

**Pull request merged**
